### ISSUE TITLE
CEF-X: Can some parameter be removed from the parameter groups?

### ISSUE THREAD

**Issue by dellerDLR** [virtualsatellite/VirtualSatellite4-CEF#169]
**Description**
The CEF-X concept contains many parameters from the normal CEF ceoncept.
But are all parameters still needed for the CEF-X version?

Some examples:
- In CEF there is a *Equipmentparameter* *unitQuantity* to define the total quantity of the unit. In EquipmentPowerParameters it can be specified how many of these units are active. In CEF-X there is no *unitQuantity*. Does it make sense that in EquipmentPowerParameters the amount of active units cna be specified?
- TBD

**Comment by franzTobiasDLR** [comment]
Also power Unit active should be removed...

Maybe check all the parameters with "unit" in their name
