### ISSUE TITLE
Inherience links are not displayed in the configuration tree

### ISSUE THREAD

**Issue by dellerDLR** [virtualsatellite/VirtualSatellite4-CEF#174]
When adding elements to the configuration tree with drag n drop and alt, only one element shows the inheritence in the tree.

![image](https://github.com/virtualsatellite/VirtualSatellite4-CEF/assets/95470420/0f417a37-680f-4f36-b326-11ff5a2ad21d)

If you click on refresh, they dissappear completly.

![image](https://github.com/virtualsatellite/VirtualSatellite4-CEF/assets/95470420/82b7c258-9940-4851-9295-5e110f8d5b15)

**Comment by dellerDLR** [comment]
Maybe caused by #176

**Comment by franzTobiasDLR** [comment]
Didn't see it anymore... Let's close it for now.
