### ISSUE TITLE
Enable CEF Concept for extended Product Structures

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-CEF#7]
The Configuration of a spacecraft should follow aprototype pattern approach.

As already implemented in the extended Product Structures of virtualsatellite/VirtualSatellite-Core a product should be defined first, and then added and integrated into the configuration.

- [x] Adapt UI
- [x] Adapt test cases
- [x] Integrate into build process

**Comment by SaMuellerDLR** [comment]
Done in PL #31
